# Generated by Django 5.0.4 on 2024-06-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grid',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'managed': False},
        ),
    ]
