# Generated by Django 5.0.4 on 2024-06-04 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_grid_table_alter_task_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grid',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
