# Generated by Django 5.0.4 on 2024-06-04 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_grid_options_alter_task_options'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='grid',
        #     name='minute',
        # ),
        # migrations.RemoveField(
        #     model_name='grid',
        #     name='time',
        # ),
        migrations.AddField(
            model_name='grid',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='add_to_checklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grid',
            name='coloured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grid',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='etime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='stime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
