# Generated by Django 5.0.4 on 2024-06-05 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_grid_table_alter_task_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grid',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'managed': False},
        ),
    ]
