# Generated by Django 5.0.4 on 2024-06-05 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_grid_options_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grid',
            table='grid',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
