# Generated by Django 5.0.4 on 2024-06-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_grid_table_alter_task_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grid',
        ),
    ]
